name: CI/CD for Airflow on GCP

on:
  push:
    branches:
      - main   # triggers when code is pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.GCP_VM_HOST }} >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa learning_subscriptions25@34.32.124.224

      - name: Deploy code to GCP VM
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_HOST }} << 'EOF'
            # Set project folder
            PROJ_DIR=/home/learning_subscriptions25/cloud-airflow-data-pipeline
            AIRFLOW_DIR=/home/learning_subscriptions25/airflow

            # Create parent folder if it doesn't exist
            mkdir -p "$(dirname "$PROJ_DIR")"

            # Clone repo if folder doesn't exist, otherwise pull updates
            if [ ! -d "$PROJ_DIR/.git" ]; then
              git clone https://github.com/Hashem-Qaryouti/cloud-airflow-data-pipeline.git
            else
              cd "$PROJ_DIR"
              git pull origin main
            fi
            cp -r $PROJ_DIR/dags/* $AIRFLOW_DIR/dags/
          EOF
